services:
   redis: 
     image: redislabs/redismod
     container_name: redis_ask3
     ports:
       - '6379:6379' 
   web:
        build: .
        container_name: web_ask3
        ports:
            - "5000:5000"
        volumes:
            - .:/project
        depends_on:
            - redis
